version: 0.2

phases:
  build:
    commands:
      - echo "Packaging Earthquake Lambda..."
      - rm -rf earthquake_build
      - mkdir earthquake_build
      - cp -r earthquake/* earthquake_build/
      - cd earthquake_build
      - zip -r ../earthquake.zip .
      - cd ..

      - echo "Packaging Weather Lambda..."
      - rm -rf weather_build
      - mkdir weather_build
      - cp -r weather/* weather_build/
      - cd weather_build
      - zip -r ../weather.zip .
      - cd ..

      - echo "Packaging Employee Lambda..."
      - rm -rf employee_build
      - mkdir employee_build
      - cp -r employee/* employee_build/
      - cd employee_build
      - zip -r ../employee.zip .
      - cd ..

      - echo "Deploying Earthquake Lambda..."
      - aws lambda update-function-code \
          --function-name Earthquake_automated_pipeline \
          --zip-file fileb://earthquake.zip

      - echo "Deploying Weather Lambda..."
      - aws lambda update-function-code \
          --function-name Weather_ETL \
          --zip-file fileb://weather.zip

      - echo "Deploying Employee Lambda..."
      - aws lambda update-function-code \
          --function-name Employee_ETL \
          --zip-file fileb://employee.zip

artifacts:
  files:
    - earthquake.zip
    - weather.zip
    - employee.zip