name: Python CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip

          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Check Earthquake Lambda
        run: |
          python -m py_compile earthquake/lambda_function.py
          python -m py_compile earthquake/fetch_data.py
          find earthquake -name "*.py" -exec python -m py_compile {} \;

      - name: Check Employee Lambda
        run: |
          find employee -name "*.py" -exec python -m py_compile {} \;

      - name: Check Weather Lambda
        run: |
          python -m py_compile weather/weather_fetch.py
          find weather -name "*.py" -exec python -m py_compile {} \;

      - name: Workflow Passed
        run: echo "GitHub Actions completed successfully."